group: edge
sudo: required

language: go
go: 
  - 1.10.3

services: 
  - docker

install:
  - go get -u github.com/golang/lint/golint

script: 
  - make check && make docker-build

after_success:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - make docker-push
